import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState, useEffect, useContext } from "react";
import styled from "styled-components";
import axios from "axios";
import { AppContext } from "../contexts/context";

const queryString = `https://api.nasa.gov/planetary/apod?api_key=hK7CbhG9XjeaNGh6flMBefqAZdlGwyWhqgAWT3cj`;
const startDate = "2021-01-01";
const endDate = "2021-01-05";

const Home = () => {
    const useApp = useContext(AppContext);
    const { images, setImages, likedImages, setLikedImages } = useApp;

    const [isLoading, setIsLoading] = useState(false);
    const [imagesIsOpen, setImagesIsOpen] = useState(false);
    const toggleImagesOpen = () => {
        setImagesIsOpen(!imagesIsOpen);
    };
    useEffect(async () => {
        setIsLoading(true);
        try {
            const { data } = await axios.get(
                queryString + `&start_date=${startDate}&end_date=${endDate}`,
                {}
            );

            setImages(data);
            const liked = [];
            data.forEach(() => {
                liked.push(false);
            });
            setLikedImages(liked);

            console.log(data);
        } catch (e) {
            console.error(e);
        }
        setIsLoading(false);
    }, []);

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>Welcome to Spacestagram!</h1>

                <p className={styles.description}>
                    Get started by clicking search below :)
                </p>

                <SearchButton className={styles.card}>
                    <h2>Search &rarr;</h2>
                    <p>Discover a world of spacey pics 🚀</p>
                </SearchButton>
                {isLoading && <div>Loading!!!</div>}
                {imagesIsOpen ? (
                    <ImagesDiv>
                        {images.map((image, index) => {
                            return (
                                <Card key={index}>
                                    <h2>{image.title} &rarr;</h2>
                                    <p>{image.explanation}</p>
                                    <Image
                                        width={300}
                                        height={200}
                                        src={image.url}
                                    ></Image>
                                    <p>🎨: {image.copyright}</p>
                                    {true ? <p>liked!</p> : <p>not liked :(</p>}
                                </Card>
                            );
                        })}
                    </ImagesDiv>
                ) : (
                    <button onClick={toggleImagesOpen}>Expand Images!</button>
                )}
            </main>
        </div>
    );
};

const ImagesDiv = styled.div`
    height: 100%;
`;

const Card = styled.div`
    margin: 1rem;
    padding: 1.5rem;
    text-align: left;
    color: inherit;
    text-decoration: none;
    border: 1px solid #eaeaea;
    border-radius: 10px;
    transition: color 0.15s ease, border-color 0.15s ease;
    width: 45%;
    background: white;
`;

const SearchButton = styled.button`
    margin: 1rem;
    padding: 1.5rem;
    text-align: left;
    color: inherit;
    text-decoration: none;
    border: 1px solid #eaeaea;
    border-radius: 10px;
    transition: color 0.15s ease, border-color 0.15s ease;
    width: 45%;
    background: white;
    cursor: pointer;
`;

export default Home;
